# .
# .  Read the tutorial at: http://dev.bukkit.org/bukkit-plugins/holographic-displays/
# .
# .  Plugin created by filoghost.
# .
space-between-lines: 0.02
images:
  symbol: '[x]'
  transparency:
    space: ' [|] '
    color: '&7'
update-notification: true
bungee:
  refresh-seconds: 3
  use-RedisBungee: false
  pinger:
    enable: false
    timeout: 500
    offline-motd: '&c&lOffline, couldn''t get the MOTD.'
    status:
      online: '&a&lOnline'
      offline: '&c&lOffline'
    motd-remove-leading-trailing-spaces: true
    servers:
    - 'hub: 127.0.0.1:25565'
    - 'survival: 127.0.0.1:25566'
    - 'minigames: 127.0.0.1:25567'
time:
  format: H:mm
  zone: GMT+1
debug: false
precise-hologram-movement: true
