savebackconfig: true
configversion:
  notify: true
  created: 741
  saved: 785
logging:
  active: true
  maxqueuesize: 5000
  extended:
    status: false
  backend:
    console:
      active: true
      prefix: '&4&l[NoCheatPlus] '
      asynchronous: true
    file:
      active: true
      prefix: ''
      filename: nocheatplus.log
    ingamechat:
      active: true
      prefix: '&6&l[&5&lTEST&4&lNCP&6&l]: &e&l'
      subscriptions: false
data:
  expiration:
    active: false
    duration: 60
    history: false
  consistencychecks:
    active: true
    interval: 10
    maxtime: 2
    suppresswarnings: false
protection:
  plugins:
    hide:
      active: true
      nopermission:
        message: '&cI''m sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe that this is in error.'
        commands:
        - plugins
        - version
        - icanhasbukkit
      unknowncommand:
        message: Unknown command. Type "/help" for help.
        commands: []
  commands:
    consoleonly:
      active: false
      message: '&c&lI''m sorry, but this command can''t be executed in chat. Use the console instead!'
      commands:
      - op
      - deop
  clients:
    motd:
      active: true
      allowall: false
checks:
  blockbreak:
    direction:
      active: true
      actions: cancel vl>10 log:bdirection:0:5:if cancel
    fastbreak:
      active: true
      strict: true
      delay: 100
      intervalsurvival: 100
      grace: 2000
      actions: cancel vl>0 log:fastbreak:3:5:cif cancel
    frequency:
      active: true
      intervalcreative: 95
      intervalsurvival: 45
      shortterm:
        ticks: 5
        limit: 7
      actions: cancel vl>5 log:bbfrequency:3:5:if cancel vl>60 log:bbfrequency:0:5:cif cancel cmd:kickfrequency
    noswing:
      active: true
      actions: cancel vl>10 log:noswing:0:5:if cancel
    reach:
      active: true
      actions: cancel vl>5 log:breach:0:2:if cancel
    wrongblock:
      active: true
      level: 10
      actions: cancel vl>10 log:bwrong:0:5:if cancel vl>30 log:bwrong:0:5:cif cancel cmd:kickwb
  blockinteract:
    direction:
      active: true
      actions: cancel vl>10 log:bdirection:0:3:if cancel
    reach:
      active: true
      actions: cancel vl>5 log:breach:0:2:if cancel
    speed:
      active: true
      interval: 2000
      limit: 60
      actions: cancel vl>200 log:bspeed:0:2:if cancel vl>1000 cancel log:bspeed:0:2:icf cmd:kickbspeed
    visible:
      active: true
      actions: cancel vl>100 log:bvisible:0:10:if cancel
  blockplace:
    against:
      active: true
      actions: cancel
    autosign:
      active: true
      skipempty: false
      actions: cancel vl>10 log:bautosign:0:3:if cancel
    direction:
      active: true
      actions: cancel vl>10 log:bdirection:0:3:if cancel
    fastplace:
      active: true
      limit: 22
      shortterm:
        ticks: 10
        limit: 6
      actions: cancel vl>100 log:fastplace:3:5:cif cancel
    reach:
      active: true
      actions: cancel vl>5 log:breach:0:2:if cancel
    noswing:
      active: true
      exceptions:
      - WATER_LILY
      - FLINT_AND_STEEL
      actions: cancel vl>10 log:noswing:0:5:if cancel
    speed:
      active: true
      interval: 45
      actions: cancel vl>150 log:bpspeed:3:5:if cancel vl>1000 log:bpspeed:3:5:cif cancel
  chat:
    color:
      active: true
      actions: log:color:0:1:if cancel
    commands:
      active: true
      exclusions: []
      handleaschat:
      - me
      level: 10
      shortterm:
        ticks: 18
        level: 3
      actions: log:commands:0:5:cf cancel cmd:kickcommands vl>20 log:commands:0:5:cf cancel cmd:tempkick1
    captcha:
      active: false
      characters: abcdefghjkmnpqrtuvwxyzABCDEFGHJKMNPQRTUVWXYZ2346789
      length: 6
      question: '&cPlease type ''&6[captcha]&c'' to continue sending messages/commands.'
      success: '&aOK, it sounds like you''re not a spambot.'
      tries: 3
      actions: cancel cmd:kickcaptcha vl>4 log:captcha:2:5:cf cancel cmd:kickcaptcha
    text:
      active: true
      allowvlreset: true
      frequency:
        normal:
          minimum: 0.0
          factor: 0.9
          weight: 6
          level: 160
          actions: cancel cmd:tellchatnormal vl>7 log:chatnormal:0:5:f cancel cmd:tellchatnormal vl>20 log:chatnormal:0:5:cf cancel cmd:kickchatnormal vl>40 log:chatnormal:0:5:cf cancel cmd:kickchat5
        shortterm:
          minimum: 2.0
          factor: 0.7
          weight: 3.0
          level: 20.0
          actions: log:chatfast:0:5:cf cancel cmd:kickchatfast vl>20 log:chatfast:0:5:cf cancel cmd:kickchat1 vl>40 log:chatfast:0:5:cf cancel cmd:kickchat5
      message:
        lettercount: 1.0
        partition: 1.0
        uppercase: 1.0
        afterjoin: 1.5
        nomoving: 1.5
        repeatviolation: 1.0
        repeatglobal: 1.0
        repeatself: 1.5
        words:
          lengthav: 1.0
          lengthmsg: 1.0
          noletter: 0.0
      global:
        active: true
        weight: 1.0
        words:
          active: false
        prefixes:
          active: false
        similarity:
          active: false
      player:
        active: true
        words:
          active: false
        prefixes:
          active: false
        similarity:
          active: false
    warning:
      active: true
      level: 67
      message: |-
        &e&l>>>
        &e&l>>> &4&lYou Are Not Spam Chat
        &e&l>>>
      timeout: 10
    relog:
      active: true
      timeout: 5000
      warning:
        message: '&c&lYou relogged really fast! If you keep doing that, you''re going to be banned!!!.'
        number: 1
        timeout: 60000
      kickmessage: Too fast re-login, try with a little delay.
      actions: log:relog:0:10:cf cancel vl>20 log:relog:0:10:cf cancel cmd:tempkick5
    logins:
      active: true
      startupdelay: 600
      perworldcount: false
      seconds: 10
      limit: 10
      kickmessage: Too many people logging in, retry soon.
  combined:
    bedleave:
      active: true
      actions: cancel log:bedleave:0:5:if cmd:kickbedleave
    enderpearl:
      active: true
      preventclickblock: true
    improbable:
      active: true
      level: 300
      actions: cancel log:improbable:2:8:if
    invulnerable:
      active: true
      triggers:
        always: false
        falldistance: true
      initialticks:
        join: -1
      ignore:
      - FALL
      modifiers:
        all: 0
    munchhausen:
      active: false
      actions: cancel vl>100 cancel log:munchhausen:0:60:if
    yawrate:
      rate: 380
      penalty:
        factor: 1.0
        minimum: 250
        maximum: 2000
      improbable: true
  fight:
    canceldead: true
    toolchangepenalty: 500
    pvp:
      knockbackvelocity: default
    yawrate:
      active: true
    angle:
      active: true
      threshold: 50
      actions: cancel vl>100 log:angle:3:5:f cancel vl>250 log:angle:0:5:cif cancel
    critical:
      active: true
      falldistance: 0.06251
      actions: cancel vl>50 log:critical:0:5:cif cancel
    direction:
      active: true
      strict: false
      penalty: 500
      actions: cancel vl>5 log:fdirection:3:5:f cancel vl>20 log:fdirection:0:5:if cancel vl>50 log:fdirection:0:5:cif cancel
    fastheal:
      active: true
      interval: 4000
      buffer: 1000
      actions: cancel vl>10 cancel log:fastheal:0:10:i vl>30 cancel log:fastheal:0:10:if
    godmode:
      active: true
      minage: 1100
      maxage: 5000
      actions: log:godmode:2:5:if cancel vl>60 log:godmode:2:5:icf cancel
    noswing:
      active: true
      actions: cancel vl>10 log:noswing:0:5:if cancel
    reach:
      active: true
      survivaldistance: 4.4
      penalty: 500
      reduce: true
      reducedistance: 0.9
      reducestep: 0.15
      actions: cancel vl>10 log:freach:2:5:if cancel
    selfhit:
      active: true
      actions: log:fselfhit:0:5:if cancel vl>10 log:fselfhit:0:5:icf cancel cmd:kickselfhit
    speed:
      active: true
      limit: 15
      actions: log:fspeed:0:5:if cancel
      shortterm:
        ticks: 7
        limit: 6
  inventory:
    drop:
      active: true
      limit: 100
      timeframe: 20
      actions: log:drop:0:1:cif cancel cmd:dropkick:0:1
    fastclick:
      active: true
      sparecreative: true
      tweaks1_5: true
      limit:
        shortterm: 4
        normal: 15
      actions: cancel vl>50 log:fastclick:3:5:cif cancel
    instantbow:
      active: true
      strict: true
      delay: 130
      actions: cancel vl>15 log:instantbow:2:5:if cancel
    instanteat:
      active: true
      actions: log:instanteat:2:5:if cancel
    fastconsume:
      active: true
      duration: 0.7
      whitelist: false
      items: []
      actions: log:fastconsume:2:5:if cancel
    gutenberg:
      active: true
      actions: cancel log:gutenberg:0:10:icf cmd:kickinvaliddata
    items:
      active: true
    open:
      active: true
      close: true
      cancelother: true
  moving:
    creativefly:
      active: true
      ignoreallowflight: false
      ignorecreative: false
      model:
        creative:
          horizontalspeed: 100
          verticalspeed: 100
          maxheight: 128
      actions: log:flyshort:3:5:f cancel vl>100 log:flyshort:0:5:if cancel vl>400 log:flylong:0:5:cif cancel
    morepackets:
      active: true
      seconds: 6
      epsideal: 20
      epsmax: 22
      burst:
        packets: 40
        directviolation: 60
        epmviolation: 180
      actions: cancel vl>10 log:morepackets:0:2:if cancel vl>100 log:morepackets:0:2:if cancel cmd:kickpackets
    morepacketsvehicle:
      active: true
      actions: cancel vl>10 log:morepackets:0:2:if cancel
    nofall:
      active: true
      dealdamage: true
      resetonviolation: false
      resetonteleport: false
      resetonvehicle: true
      anticriticals: true
      actions: log:nofall:0:5:if cancel vl>30 log:nofall:0:5:icf cancel
    passable:
      active: true
      raytracing:
        active: true
        blockchangeonly: false
      actions: cancel vl>10 log:passable:0:5:if cancel vl>50 log:passable:0:5:icf cancel
      untracked:
        teleport:
          active: true
        command:
          active: true
          tryteleport: true
          prefixes:
          - sethome
          - home set
          - setwarp
          - warp set
          - setback
          - set back
          - back set
    survivalfly:
      active: true
      extended:
        vertical-accounting: true
      falldamage: true
      actions: log:flyshort:3:10:f cancel vl>100 log:flyshort:0:10:if cancel vl>400 log:flylong:0:5:cif cancel vl>1500 log:flylong:0:5:cif cancel cmd:kickfly
      hover:
        active: true
        step: 5
        ticks: 85
        loginticks: 0
        falldamage: true
        sfviolation: 500
    trace:
      size: 60
      mergedist: 0.9752
    vehicles:
      preventdestroyown: true
      enforcelocation: true
    velocity:
      graceticks: 20
      activationcounter: 80
      activationticks: 140
      strictinvalidation: true
    tempkickillegal: true
    loadchunks:
      join: true
    sprintinggrace: 2.0
    assumesprint: true
    speedgrace: 4.0
    enforcelocation: true
  net:
    flyingfrequency:
      active: true
      seconds: 5
      packetspersecond: 60
      actions: cancel
      reduceredundant:
        active: true
        seconds: 3
        actions: cancel
    keepalivefrequency:
      active: true
      actions: cancel vl>10 cancel log:keepalive:0:10:if vl>40 cancel log:keepalive:0:10:icf vl>100 cancel log:keepalive:0:10:icf cmd:kickalive
    sounddistance:
      active: true
      maxdistance: 320
strings:
  angle: '[player] failed [check]: VL [violations].'
  ban: ban [player]
  ban-ip: ban-ip [ip]
  bautosign: '&a&l[player] &4&lfailed &c&l[check]: &d&l->[tags]. &e&lVL &b&l[violations].'
  bbfrequency: '&a&l[player] &4&lfailed &c&l[check]: &e&lVL &b&l[violations].'
  bdirection: '&a&l[player] &4&lfailed &c&l[check]: &e&lVL &b&l[violations].'
  bedleave: '&a&l[player] &4&lfailed &c&l[check]: &e&lVL &b&l[violations].'
  bpspeed: '&a&l[player] &4&lfailed &c&l[check]: &e&lVL &b&l[violations].'
  breach: '&a&l[player] &4&lfailed &c&l[check]: &d&l([reachdistance]) &e&lVL &b&l[violations].'
  bspeed: '&a&l[player] &4&lfailed &c&l[check]: &e&lVL &b&l[violations].'
  bvisible: '&a&l[player] &4&lfailed &c&l[check]: &e&lVL &b&l[violations].'
  bwrong: '&a&l[player] &4&lfailed &c&l[check]: &e&lVL &b&l[violations].'
  captcha: '&a&l[player] &4&lfailed &c&lcaptcha &e&lVL &b&l[violations].'
  chatnormal: '&a&l[player] &4&lfailed &c&l[check]: &e&lVL &b&l[violations].'
  color: '&a&l[player] &4&lfailed &c&l[check]: &e&lVL &b&l[violations].'
  commands: '&a&l[player] &4&lfailed &c&l[check]: &e&lVL &b&l[violations].'
  combspeed: '&a&l[player] &4&lfailed &c&l[check]: &e&lVL &b&l[violations].'
  critical: '&a&l[player] &4&lfailed &c&l[check]: &d&l[tags] &e&lVL &b&l[violations].'
  drop: '&a&l[player] &4&lfailed &c&l[check]: &e&lVL &b&l[violations].'
  dropkick: ncp delay ncp kick [player] Dropping items too fast.
  fastbreak: '&a&l[player] &4&lfailed &c&l[check]: &d&l([blockid]) &e&lVL &b&l[violations].'
  fastclick: '&a&l[player] &4&lfailed &c&l[check]: &e&lVL &b&l[violations].'
  fastconsume: '&a&l[player] &4&lfailed &c&l[check]: &e&lVL &b&l[violations].'
  fastheal: '&a&l[player] &4&lfailed &c&l[check]: &e&lVL &b&l[violations].'
  fastplace: '&a&l[player] &4&lfailed &c&l[check]: &e&lVL &b&l[violations].'
  fdirection: '&a&l[player] &4&lfailed &c&l[check]: &e&lVL &b&l[violations].'
  flyshort: '&a&l[player] &4&lfailed &c&l[check]:  &e&lVL &b&l[violations].'
  flylong: '&a&l[player] &4&lfailed &c&l[check]: &e&lVL &b&l[violations].'
  freach: '&a&l[player] &4&lfailed &c&l[check]: &e&lVL &b&l[violations].'
  fselfhit: '&a&l[player] &4&lfailed &c&l[check]: &e&lVL &b&l[violations].'
  fspeed: '&a&l[player] &4&lfailed &c&l[check]: &e&lVL &b&l[violations].'
  gutenberg: '&a&l[player] &4&lfailed &c&l[check]: &e&lVL &b&l[violations]..'
  godmode: '&a&l[player] &4&lfailed &c&l[check]: &e&lVL &b&l[violations].'
  improbable: '&a&l[player] &4&lfailed &c&l[check]: &e&lVL &b&l[violations].'
  instantbow: '&a&l[player] &4&lfailed &c&l[check]: &e&lVL &b&l[violations].'
  instanteat: '&a&l[player] &4&lfailed &c&l[check]: &e&lVL &b&l[violations].'
  keepalive: '&a&l[player] &4&lfailed &c&l[check]: &d&l(god/freecam?). &e&lVL &b&l[violations].'
  kick: kick [player]
  kickalive: ncp kick [player] Too many keep-alive packets.
  kickbedleave: ncp delay ncp kick [player] Go find a bed!
  kickbspeed: ncp kick [player] You interacted too fast!
  kickcaptcha: ncp kick [player] Enter the captcha!
  kickchat1: ncp tempkick [player] 1 You're still not allowed to spam!
  kickchat5: ncp tempkick [player] 5 You're not intended to spam!
  kickchatfast: ncp kick &c&l[player] &4&lYou're not allowed to spam in chat!
  kickchatnormal: ncp kick [player] Too many chat messages, take a break.
  kickcommands: ncp tempkick [player] 1 You're not allowed to spam commands!
  kickfly: ncp delay ncp kick [player] Kicked for flying (or related)
  kickfrequency: ncp kick [player] You did something too fast!
  kickgod: ncp kick [player] God mode?
  kickinvaliddata: ncp kick [player] Invalid data.
  kickpackets: ncp delay ncp kick [player] Too many packets (extreme lag?)
  kickselfhit: ncp kick [player] You tried to hit yourself!
  kickwb: ncp kick [player] Block breaking out of sync!
  knockback: '&a&l[player] &4&lfailed &c&l[check]: &e&lVL &b&l[violations].'
  morepackets: '&a&l[player] &4&lfailed &c&l[check]: &e&lVL &b&l[violations].'
  munchhausen: '&a&l[player] &4&lfailed &c&l[check]: &e&lVL &b&l[violations].'
  nofall: '&a&l[player] &4&lfailed &c&l[check]: &e&lVL &b&l[violations].'
  chatfast: '&a&l[player] &4&lfailed &c&l[check]: &d&l(IP: [ip]). &e&lVL &b&l[violations].'
  noswing: '&a&l[player] &4&lfailed &c&l[check]: &e&lVL &b&l[violations].'
  passable: '&a&l[player] &4&lfailed &c&l[check]: &d&l([blockid]). &e&lVL &b&l[violations].'
  relog: '&a&l[player] &4&lfailed &c&l[check]: &e&lVL &b&l[violations].'
  tellchatnormal: 'ncp tell [player] &c&lNCP: &e&lToo many messages, slow down...'
  tempkick1: ncp tempkick [player] 1 Wait a minute!
  tempkick5: ncp tempkick [player] 5 You have five minutes to think about it!
compatibility:
  exemptions:
    remove:
      join: true
      leave: true
  managelisteners: false
  bukkitapionly: false
  blocks:
    ignorepassable:
    - WOODEN_DOOR
    - IRON_DOOR_BLOCK
    - TRAP_DOOR
    - PISTON_EXTENSION
    - PISTON_MOVING_PIECE
    allowinstantbreak: []
    overrideflags:
      snow: default
