# This is what people call a COMMENT. Comments are ignored by bukkit, so I can write whatever I want!
# 
# Hi! Thanks for downloading this plugin! As you can see, 
# this plugin has pretty awesome stuff. You probably came here to change some values and
# stuff. Well, you came to the right place. 
# 
# The 'automatic-drugs' field (which is under 'settings') is probably the most important. It's whether or not you want your drugs to automatically rename/be usable.
# This is useful for servers who want the ability to have, for example, Cactus Green, AND Marijuana.
# This field's default value is true. Set it to false if you want to disable it.
# When disabled, you simply have to put the drug's item in a crafting table. It will turn it into a real, renamed, usable drug.
# 
# The 'acid-trip' field (which is under 'settings') is the kind of trip you want Acid to have. It takes either 'good', or 'bad'.
# 
# The 'enabled' field (which is under 'quick-drug-shop', which is under 'settings') is whether or not you want a shop pop up when right clicking (and sneaking) with a emerald in your hand!
# This quick shop will substract emerald from your inventory depending on which drug you bought. If you're in creative, it will not cost any emeralds.
# Its default value is false. Set it to true to enable it.
# 
# The 'window-title' field (which is under 'quick-drug-shop', which is under 'settings') is the title of the Quick Drug Shop window.
# It will not come in effect if the quick drug shop is disabled.
# Its default value is 'Quick Drug Shop'.The 'permission' field (which is under 'quick-drugs-shop', which is under 'settings') is the permission you need to open the Quick Drug Shop.
# 
# The 'price' field under accessories is how much it costs to buy some in the Quick Drug Shop.The 'poison-bread-permission' field, which is under settings, is the permission required to poison bread with cyanide.
# 
# The 'name' field is where you set a drug's name!
# Example: &2Marijuana
# 
# The 'message' field is what is sent to you when you used a drug!
# Example: "You just smoked some Marijuana!"
# 
# The 'error' field is the error sent to you when you don't have the required materials to use that drug.
# This only applies to Meth, Weed, and Meridiem.
# Example: "You need a flint and steel to smoke this!"
# 
# The 'tooHigh' field is the message sent to you when you try to take a drug that you're still under the influence of.
# Example: "You're too high to smoke Marijuana!"
# 
# The 'price' field is how many emeralds it costs to get a stack of this drug with the Quick Drug Shop.
# 
# The 'nausea' field is whether or not nausea is enabled for this drug. true or false.The 'use-permission' field is the permission a user is required to have before using this drug.
# Example: drugsxl.use.marijuana
# 
# The 'get-permission' field is the permission a user is required to have before creating a drug with a crafting table, or getting
# the drug automatically renamed in his hands.
# Example: drugsxl.get.marijuana
# 
# The 'burntOut' field, which only applies to Caffeine Pills, is the message given to the Player when he's burnt out.
# Example: "You're burnt out!"
# 
# The 'slur' field, which doesn't apply to Cyanide, is whether or not you want this drug to affect your chat text. If you need to see this in action,
# then simply head over to the plugin page and read about it, or click on the video plugin review!
# It will be set to true by default. Set it to false if you want to disable it.
# 
# The 'slur-text' field, which only applies to Marijuana, Cocaine, and Ecstasy, is the kind of speech slurs you want.
# Each drug have a different kind of speech slur, so the input isn't the same for all of them.
# 
# Marijuana's slur-text is simply a word, or a phrase. By default, it's '.. uh.. ', and it will replace all spaces with this piece of text.
# 
# Cocaine's slur-text is multiple characters. Those are the characters you want to replace with &k (magical text). By default, it's set to 0-9aeiouyAEIOUY.
# This means that every number and all vowels will be affected by the &k text. If you know Java Regex, you can use it.
# If you wanted to use the whole alphabet, you could do a-z. It's recommended you just list out all the letters, though.
# Cocaine's slur letters are CASE SENSITIVE! So don't forget to put the upper case versions of your added letters!
# Note: Do NOT put special characters in Cocaine's speech slur list!
# 
# Ecstasy's slur-text is simply a list of emoticons. Yes, that sounds silly, but that's what Ecstasy's slur is.
# To make a list of emoticons, you need to simply use a list format. Like this:
# slur-text:
# - ':D'
# - '(:'
# - 'You can use text'
# - 'if you're feeling fancy'
# - 'just never'
# - 'add new items'
# - 'they will not come in action'
# - 'only the 8 first. (counting 0 to 7)'
# That's simply it! Ecstasy will randomly put these emoticons before, and after the user's text if they're on ecstasy.
# When changing text in ecstasy, always put 'single quotes' around it. It will ensure safety. If not, you will most likely
# get 'null' instead of your emoticon.
# 
# The 'item-id' field is the ITEM ID for the said drug.
# The 'item-data' field is a bit more complicated. It's the item's data.
# Usually, 'data' stays at 0. But, on some items, like dyes, wood, and leaves, they will have a value.
# If you're familiar with worldedit, then you'll understand what I mean. See, let's say I wanted some birch wood plank as my drug.
# I would put this:
# item-id: 5
# item-data: 2
# The DATA would be 2, because it's the second item of the wooden planks family.
# It's the same as saying in worldedit '//set 5:2'
# If you want to find out an item's data value/id, go in Minecraft and press F3+H. It will show a item's information.
# While having that special mode on, hover over an item. Besides the name it will show its information like so:
# Birch Wood Planks (#0005/2)
# What comes after the slash is the data value. If you're still confused, go Google 'item data values'.


Settings:
  automatic-drugs: true
  acid-trip: bad
  quick-drug-shop:
    enabled: false
    window-title: Quick Drug Shop
    permission: drugsxl.shop
  accessories:
    meth-pipe:
      price: 5
    paper:
      price: 5
    lighter:
      price: 5
    golden-straw:
      price: 15
  poison-bread-permission: drugsxl.poisonbread
Drugs:
  METH:
    name: '&5Metanfetamina'
    message: Hai fumato Metanfetamina!
    error: Per fumare risulta necessario un acciarino e un lingotto di ferro Metanfetamina.
    tooHigh: Livello troppo alto per fumare Metanfetamina.
    price: 15
    nausea: true
    use-permission: drugsxl.use.meth
    get-permission: drugsxl.get.meth
    slur: true
    item-id: 406
    item-data: 0
  COCAINE:
    name: '&bCocaina'
    message: Hai sniffato Cocaina!
    tooHigh: Livello troppo alto per sniffare Cocaina.
    price: 15
    nausea: true
    use-permission: drugsxl.use.cocaine
    get-permission: drugsxl.get.cocaine
    slur: true
    slur-text: 0-9aeiouyAEIOUY
    item-id: 353
    item-data: 0
  MERIDIEM:
    name: '&eMeridiem'
    message: Ne hai sbuffato un po di Meridiem!
    error: Hai bisogno di una cannuccia dorata per sbuffare Meridiem.
    tooHigh: Livello troppo alto per sbuffare Meridiem.
    price: 20
    nausea: true
    use-permission: drugsxl.use.meridiem
    get-permission: drugsxl.get.meridiem
    slur: true
    item-id: 348
    item-data: 0
  MARIJUANA:
    name: '&2Marijuana'
    message: Hai fumato la Marijuana!
    error: Server un acciarino e della carta per fumare la Marijuana.
    tooHigh: Livello troppo alto per fumare Marijuana.
    price: 5
    nausea: true
    use-permission: drugsxl.use.marijuana
    get-permission: drugsxl.get.marijuana
    slur: true
    slur-text: '.. uh.. '
    item-id: 351
    item-data: 2
  CAFFEINE:
    name: '&cCaffeina'
    message: Hai ingerito alcune pillole di caffeina!
    tooHigh: Livello troppo alto per ingerire la caffeina.
    price: 1
    nausea: false
    use-permission: drugsxl.use.caffeine
    get-permission: drugsxl.get.caffeine
    slur: true
    burntOut: Sei bruciato!
    item-id: 362
    item-data: 0
  ECSTASY:
    name: '&dEcstasy'
    message: Ne hai ingoiato un po di Ecstasy!
    tooHigh: Livello troppo alto per assumere pillole di Ecstasy.
    price: 10
    nausea: true
    use-permission: drugsxl.use.ecstasy
    get-permission: drugsxl.get.ecstasy
    slur: true
    slur-text:
    - :)
    - :D
    - '(:'
    - :3
    - 'c:'
    - <3
    - <333
    - <33333
    item-id: 351
    item-data: 9
  CYANIDE:
    name: '&8Cyanide'
    message: Hai ingoiato la pillola di Cyanide!
    tooHigh: Tu ora sei avvelenato.
    price: 5
    nausea: false
    use-permission: drugsxl.use.cyanide
    get-permission: drugsxl.get.cyanide
    item-id: 351
    item-data: 5
  ACID:
    name: '&6Acido'
    message: Hai preso un po di acido!
    tooHigh: Tu ora sei intrappolato in un trip.
    price: 20
    nausea: true
    use-permission: drugsxl.use.acid
    get-permission: drugsxl.get.acid
    slur: true
    item-id: 351
    item-data: 14
